name: Run Discord Bot

on:
  schedule:
    - cron: "0 8 * * *"   # каждый день в 08:00 UTC
  workflow_dispatch:       # кнопка Run workflow

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Скачиваем репозиторий (фиксированный SHA)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Устанавливаем Python (фиксированный SHA)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Устанавливаем зависимости
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Запуск бота
      - name: Run Discord Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python bot.py
